---
version: "2"
linters:
  enable:
    - errname
    - errorlint
    - goconst
    - gocritic
    - godot
    - gosec
    - predeclared
    - unparam
    - whitespace
    - wsl
  settings:
    gocritic:
      enabled-checks:
        - importShadow
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/statnett/controller-runtime-viper
