name: build the package
on: [push, fork, pull_request, workflow_dispatch]
jobs:
  build-package:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build ./...

