name: staticcheck
on: [push, fork, pull_request, workflow_dispatch]
jobs:
  run-staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
          working-directory: "pkg/zap"
