name: staticcheck
on:
  pull_request:
jobs:
  run:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
