name: Run unit tests
on: [push, fork, pull_request, workflow_dispatch]
jobs:
  run-tests:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go vet check
        run: |
          go vet ./...
      - name: Gofmt check
        run: |
          diff=`go fmt ./...`
          if [[ -n "${diff}" ]]; then
            echo "Gofmt check failed :"
            echo "${diff}"
            exit 1
          fi
      - name: Go test
        run: |
          go test -v 2>&1 ./... -coverprofile cover.out -covermode count | tee test-report.txt


